(* GENERATED by scripts/generate-runtime-bridge-v2.mjs. DO NOT EDIT. *)
theory TRUST_Runtime_Bridge_Generated
  imports TRUST_Concrete_Configuration
begin

definition runtime_bridge_schema_sha256 :: string where
  "runtime_bridge_schema_sha256 = ''20516f2e63a9cef94da420d65345076c307374cef65c543983de99ea9ae93aaf''"

definition native_runtime_template_sha256 :: string where
  "native_runtime_template_sha256 = ''b82010913d2b6f1f7778c48d05a63e73c7498b62f8829f0ed33a86783c0667c1''"
definition native_runtime_bytes :: nat where "native_runtime_bytes = 20043"
definition profile_adapter_runtime_sha256 :: string where
  "profile_adapter_runtime_sha256 = ''2a7214a83e298e02e85bcfddeb022f0f339bd6cd616e0c7333247728c32f2541''"
definition profile_adapter_runtime_bytes :: nat where "profile_adapter_runtime_bytes = 19218"
definition profile_governor_runtime_sha256 :: string where
  "profile_governor_runtime_sha256 = ''ba2d63c8e93db7997ce57fe128a36dcfa761fb993e5babc9920d2911764f358e''"
definition profile_governor_runtime_bytes :: nat where "profile_governor_runtime_bytes = 2790"
definition eip170_runtime_limit :: nat where "eip170_runtime_limit = 24576"

definition kernel_interface_id :: nat where "kernel_interface_id = 721552136"
definition native_route_interface_id :: nat where "native_route_interface_id = 1557713415"
definition verified_profile_interface_id :: nat where "verified_profile_interface_id = 2997643143"

definition action_calldata_length :: nat where "action_calldata_length = 644"
definition reversal_calldata_length :: nat where "reversal_calldata_length = 388"
definition action_word_count :: nat where "action_word_count = 20"
definition reversal_word_count :: nat where "reversal_word_count = 12"
definition action_enum_words :: "(nat \<times> nat) list" where "action_enum_words = [(2, 6)]"
definition action_address_words :: "nat list" where "action_address_words = [3, 4, 5, 6]"
definition action_uint64_words :: "nat list" where "action_uint64_words = [10, 16]"
definition action_uint48_words :: "nat list" where "action_uint48_words = [18, 19]"
definition reversal_enum_words :: "(nat \<times> nat) list" where "reversal_enum_words = [(3, 3)]"
definition reversal_address_words :: "nat list" where "reversal_address_words = []"
definition reversal_uint64_words :: "nat list" where "reversal_uint64_words = [5, 8]"
definition reversal_uint48_words :: "nat list" where "reversal_uint48_words = [10, 11]"

definition action_entrypoint_selector :: nat where
  "action_entrypoint_selector = 793642867"
definition reversal_entrypoint_selector :: nat where
  "reversal_entrypoint_selector = 730410639"
definition native_route_action_selector :: nat where
  "native_route_action_selector = 1084868755"
definition native_route_reversal_selector :: nat where
  "native_route_reversal_selector = 477174420"
definition trust_rejected_selector :: nat where
  "trust_rejected_selector = 2364935023"
definition trust_operational_failure_selector :: nat where
  "trust_operational_failure_selector = 946785368"
definition trust_unauthorized_selector :: nat where
  "trust_unauthorized_selector = 2573951284"
definition trust_replay_selector :: nat where
  "trust_replay_selector = 1921260329"
definition trust_invalid_command_selector :: nat where
  "trust_invalid_command_selector = 3982638099"
definition trust_terminal_selector :: nat where
  "trust_terminal_selector = 2799851459"
definition trust_route_mismatch_selector :: nat where
  "trust_route_mismatch_selector = 1125585636"
definition generic_dispatcher_input_selector :: nat where
  "generic_dispatcher_input_selector = 4294967295"
definition typed_command_entrypoint_selectors :: "nat set" where
  "typed_command_entrypoint_selectors =
    {action_entrypoint_selector, reversal_entrypoint_selector,
     native_route_action_selector, native_route_reversal_selector}"
definition typed_failure_selectors :: "nat set" where
  "typed_failure_selectors =
    {trust_rejected_selector, trust_operational_failure_selector, trust_unauthorized_selector, trust_replay_selector, trust_invalid_command_selector, trust_terminal_selector}"

fun solidity_action_code :: "legal_action_kind \<Rightarrow> nat" where
  "solidity_action_code Legal_Freeze = 0"
| "solidity_action_code Legal_Seize = 1"
| "solidity_action_code Legal_Confiscate = 2"
| "solidity_action_code Legal_Liquidate = 3"
| "solidity_action_code Legal_Restrict = 4"
| "solidity_action_code Legal_Recover = 5"

fun solidity_reversal_code :: "trust_reversal_kind \<Rightarrow> nat" where
  "solidity_reversal_code TRUST_UNFREEZE = 0"
| "solidity_reversal_code TRUST_RELEASE = 1"
| "solidity_reversal_code TRUST_UNRESTRICT = 2"

datatype trust_route_class =
    Route_Kernel_Command
  | Route_Kernel_View
  | Route_Native_Exact_Use
  | Route_ERC7943_Sensitive
  | Route_ERC7943_View
  | Route_ERC20_Mutator
  | Route_ERC20_View
  | Route_Governance
  | Route_Immutable_View
  | Route_Profile_Command
  | Route_Profile_View
  | Route_Seal_Command
  | Route_Seal_View

definition native_routes :: "(nat \<times> trust_route_class) list" where
  "native_routes =
    [(33540519, Route_Kernel_View),
     (117300739, Route_ERC20_View),
     (157198259, Route_ERC20_Mutator),
     (204737060, Route_Immutable_View),
     (361437783, Route_ERC7943_View),
     (404098525, Route_ERC20_View),
     (428484522, Route_Kernel_View),
     (477174420, Route_Native_Exact_Use),
     (599290589, Route_ERC20_Mutator),
     (708871729, Route_Kernel_View),
     (730410639, Route_Kernel_Command),
     (734030482, Route_ERC7943_View),
     (793642867, Route_Kernel_Command),
     (826074471, Route_ERC20_View),
     (856674270, Route_Kernel_View),
     (1084868755, Route_Native_Exact_Use),
     (1537439609, Route_Kernel_View),
     (1889567281, Route_ERC20_View),
     (2079914166, Route_Kernel_View),
     (2429776058, Route_ERC7943_View),
     (2514000705, Route_ERC20_View),
     (2680279271, Route_ERC7943_Sensitive),
     (2767997613, Route_Governance),
     (2835717307, Route_ERC20_Mutator),
     (3714247998, Route_ERC20_View),
     (3831904486, Route_ERC7943_View),
     (3957611706, Route_ERC7943_Sensitive),
     (4080097900, Route_Kernel_View),
     (4128078703, Route_Governance),
     (4234842386, Route_Kernel_View)]"

definition native_method_identifiers :: "nat list" where
  "native_method_identifiers = [33540519, 117300739, 157198259, 204737060, 361437783, 404098525, 428484522, 477174420, 599290589, 708871729, 730410639, 734030482, 793642867, 826074471, 856674270, 1084868755, 1537439609, 1889567281, 2079914166, 2429776058, 2514000705, 2680279271, 2767997613, 2835717307, 3714247998, 3831904486, 3957611706, 4080097900, 4128078703, 4234842386]"

definition profile_adapter_routes :: "(nat \<times> trust_route_class) list" where
  "profile_adapter_routes =
    [(33540519, Route_Kernel_View),
     (373319844, Route_Immutable_View),
     (428484522, Route_Kernel_View),
     (613625942, Route_Profile_Command),
     (708871729, Route_Kernel_View),
     (730410639, Route_Kernel_Command),
     (793642867, Route_Kernel_Command),
     (856674270, Route_Kernel_View),
     (1537439609, Route_Kernel_View),
     (2079914166, Route_Kernel_View),
     (2398826873, Route_Seal_Command),
     (2520733649, Route_Profile_View),
     (3212714319, Route_Immutable_View),
     (4049710945, Route_Immutable_View),
     (4080097900, Route_Kernel_View),
     (4228666474, Route_Immutable_View),
     (4234842386, Route_Kernel_View)]"

definition profile_adapter_method_identifiers :: "nat list" where
  "profile_adapter_method_identifiers = [33540519, 373319844, 428484522, 613625942, 708871729, 730410639, 793642867, 856674270, 1537439609, 2079914166, 2398826873, 2520733649, 3212714319, 4049710945, 4080097900, 4228666474, 4234842386]"

definition profile_governor_routes :: "(nat \<times> trust_route_class) list" where
  "profile_governor_routes =
    [(249044032, Route_Seal_View),
     (323885300, Route_Immutable_View),
     (1653638749, Route_Immutable_View),
     (2134638570, Route_Seal_View),
     (2194210079, Route_Seal_Command),
     (3001380254, Route_Seal_View),
     (3040142763, Route_Immutable_View),
     (3112633780, Route_Seal_View),
     (3458836473, Route_Immutable_View),
     (3571345754, Route_Seal_View),
     (4168597491, Route_Seal_View),
     (4228666474, Route_Immutable_View)]"

definition profile_governor_method_identifiers :: "nat list" where
  "profile_governor_method_identifiers = [249044032, 323885300, 1653638749, 2134638570, 2194210079, 3001380254, 3040142763, 3112633780, 3458836473, 3571345754, 4168597491, 4228666474]"

definition native_storage_slots :: "(string \<times> nat) list" where
  "native_storage_slots =
    [(''native.name'', 0),
     (''native.symbol'', 1),
     (''native.totalSupply'', 2),
     (''native.balances'', 3),
     (''native.allowances'', 4),
     (''native.frozen'', 5),
     (''native.restricted'', 6),
     (''native.custodyBacking'', 7),
     (''native.freezeHeads'', 8),
     (''native.restrictionHeads'', 9),
     (''native.authorities'', 10),
     (''native.usedNonces'', 11),
     (''native.usedGovernanceIds'', 12),
     (''native.actions'', 13),
     (''native.effects'', 14),
     (''native.receipts'', 15),
     (''native.cases'', 16),
     (''native.custody'', 17),
     (''native.consumedEntitlements'', 18),
     (''native.pendingCommitments'', 19),
     (''native.pendingReversals'', 20),
     (''native.bindings'', 21),
     (''native.dependencyRoot'', 22),
     (''native.dependencyEpoch'', 23),
     (''native.routeTicket'', 24),
     (''native.entered'', 28)]"

definition profile_adapter_storage_slots :: "(string \<times> nat) list" where
  "profile_adapter_storage_slots =
    [(''profile.adapter.entered'', 0),
     (''profile.adapter.sealed'', 1),
     (''profile.adapter.sealedBinding'', 2),
     (''profile.adapter.importManifestHash'', 3),
     (''profile.adapter.dependencyRoot'', 4),
     (''profile.adapter.dependencyEpoch'', 5),
     (''profile.adapter.bindings'', 6),
     (''profile.adapter.actions'', 7),
     (''profile.adapter.effects'', 8),
     (''profile.adapter.receipts'', 9),
     (''profile.adapter.cases'', 10),
     (''profile.adapter.custody'', 11),
     (''profile.adapter.usedNonces'', 12),
     (''profile.adapter.consumedEntitlements'', 13),
     (''profile.adapter.owned'', 14),
     (''profile.adapter.freezeHeads'', 15),
     (''profile.adapter.restrictionHeads'', 16),
     (''profile.adapter.custodyBacking'', 17)]"

definition profile_governor_storage_slots :: "(string \<times> nat) list" where
  "profile_governor_storage_slots =
    [(''profile.governor.exclusiveAdapter'', 0),
     (''profile.governor.sealedBinding'', 1),
     (''profile.governor.importManifestHash'', 2),
     (''profile.governor.topologySealed'', 3)]"

definition reason_code_registry :: "(nat \<times> string) list" where
  "reason_code_registry =
    [(1, ''DOMAIN''),
     (2, ''IDENTIFIER''),
     (3, ''TIME''),
     (4, ''AUTHORITY_EPOCH''),
     (5, ''DEPENDENCY_BINDING''),
     (6, ''SHAPE''),
     (7, ''REVERSAL_PAIRING''),
     (8, ''CUSTODY''),
     (9, ''ENTITLEMENT''),
     (10, ''CASE_CONFLICT''),
     (11, ''CURRENT_EFFECT''),
     (12, ''FREEZE_DIRECTION''),
     (13, ''NO_STATE_CHANGE''),
     (100, ''POLICY_DENIED''),
     (101, ''IDENTITY_DENIED''),
     (102, ''SETTLEMENT_DENIED''),
     (103, ''ENTITLEMENT_DENIED''),
     (200, ''DEPENDENCY_CODE_MISMATCH''),
     (201, ''DEPENDENCY_CONFIGURATION_MISMATCH''),
     (202, ''DEPENDENCY_CALL_FAILED_OR_MALFORMED''),
     (203, ''DEPENDENCY_ECHO_MISMATCH''),
     (204, ''DEPENDENCY_REPORTED_FAILURE''),
     (205, ''DEPENDENCY_UNAVAILABLE_AT_BIND''),
     (300, ''TOPOLOGY_NOT_FULL''),
     (301, ''SEAL_INVALID''),
     (302, ''TOPOLOGY_MISMATCH_AT_SEAL''),
     (303, ''IMPORT_MANIFEST_MISMATCH''),
     (304, ''UPSTREAM_STATE_NOT_OWNED''),
     (400, ''UPSTREAM_CALL_FAILED''),
     (401, ''UPSTREAM_POSTSTATE_MISMATCH''),
     (402, ''IDENTITY_REGISTRY_UNAVAILABLE''),
     (403, ''COMPLIANCE_UNAVAILABLE'')]"

definition case_transition_rule_ids :: "string list" where
  "case_transition_rule_ids =
    [''CT-1'', ''CT-2'', ''CT-3'', ''CT-4'', ''CT-5'', ''CT-6'', ''CT-7'', ''CT-8'', ''CT-9'', ''CT-10'', ''CT-11'', ''CT-12'', ''CT-13'', ''CT-14'', ''CT-15'', ''CT-16'']"

theorem action_code_is_exact:
  "set (map solidity_action_code
    [Legal_Freeze, Legal_Seize, Legal_Confiscate, Legal_Liquidate, Legal_Restrict, Legal_Recover]) = {0, 1, 2, 3, 4, 5}"
  by simp

theorem reversal_code_is_exact:
  "set (map solidity_reversal_code
    [TRUST_UNFREEZE, TRUST_RELEASE, TRUST_UNRESTRICT]) = {0, 1, 2}"
  by simp

theorem generated_calldata_lengths_are_exact:
  "action_calldata_length = 4 + 32 * action_word_count \<and>
   reversal_calldata_length = 4 + 32 * reversal_word_count"
  by (simp add: action_calldata_length_def action_word_count_def
      reversal_calldata_length_def reversal_word_count_def)

theorem runtimes_are_within_the_eip170_limit:
  "native_runtime_bytes \<le> eip170_runtime_limit \<and>
   profile_adapter_runtime_bytes \<le> eip170_runtime_limit \<and>
   profile_governor_runtime_bytes \<le> eip170_runtime_limit"
  by (simp add: native_runtime_bytes_def profile_adapter_runtime_bytes_def
      profile_governor_runtime_bytes_def eip170_runtime_limit_def)

theorem native_routes_are_exhaustive:
  "map fst native_routes = native_method_identifiers \<and> distinct native_method_identifiers"
  by (simp add: native_routes_def native_method_identifiers_def)

theorem profile_adapter_routes_are_exhaustive:
  "map fst profile_adapter_routes = profile_adapter_method_identifiers \<and>
   distinct profile_adapter_method_identifiers"
  by (simp add: profile_adapter_routes_def profile_adapter_method_identifiers_def)

theorem profile_governor_routes_are_exhaustive:
  "map fst profile_governor_routes = profile_governor_method_identifiers \<and>
   distinct profile_governor_method_identifiers"
  by (simp add: profile_governor_routes_def profile_governor_method_identifiers_def)

theorem typed_command_selectors_are_classified_as_kernel_commands:
  "(action_entrypoint_selector, Route_Kernel_Command) \<in> set native_routes \<and>
   (reversal_entrypoint_selector, Route_Kernel_Command) \<in> set native_routes \<and>
   (native_route_action_selector, Route_Native_Exact_Use) \<in> set native_routes \<and>
   (native_route_reversal_selector, Route_Native_Exact_Use) \<in> set native_routes \<and>
   (action_entrypoint_selector, Route_Kernel_Command) \<in> set profile_adapter_routes \<and>
   (reversal_entrypoint_selector, Route_Kernel_Command) \<in> set profile_adapter_routes"
  by (simp add: native_routes_def profile_adapter_routes_def action_entrypoint_selector_def
      reversal_entrypoint_selector_def native_route_action_selector_def
      native_route_reversal_selector_def)

theorem generic_dispatcher_selector_is_unclassified:
  "generic_dispatcher_input_selector \<notin> set native_method_identifiers \<and>
   generic_dispatcher_input_selector \<notin> set profile_adapter_method_identifiers \<and>
   generic_dispatcher_input_selector \<notin> set profile_governor_method_identifiers"
  by (simp add: generic_dispatcher_input_selector_def native_method_identifiers_def
      profile_adapter_method_identifiers_def profile_governor_method_identifiers_def)

theorem typed_command_selectors_are_not_failure_selectors:
  "typed_command_entrypoint_selectors \<inter> typed_failure_selectors = {}"
  by (simp add: typed_command_entrypoint_selectors_def typed_failure_selectors_def
      action_entrypoint_selector_def reversal_entrypoint_selector_def
      native_route_action_selector_def native_route_reversal_selector_def
      trust_rejected_selector_def trust_operational_failure_selector_def trust_unauthorized_selector_def trust_replay_selector_def trust_invalid_command_selector_def trust_terminal_selector_def)

theorem reason_codes_are_distinct:
  "distinct (map fst reason_code_registry)"
  by (simp add: reason_code_registry_def)

theorem case_transition_rule_ids_are_distinct:
  "distinct case_transition_rule_ids"
  by (simp add: case_transition_rule_ids_def)

end
