(* GENERATED by scripts/generate-current-profile-runtime-bridge-v1.mjs. DO NOT EDIT. *)
theory TRUST_Runtime_Bridge_Current_Profile_Generated
  imports TRUST_Runtime_Bridge_Generated
begin

definition current_profile_bridge_schema_sha256 :: string where
  "current_profile_bridge_schema_sha256 = ''2aa641af1f362bbe1aaa246edfd22045999903a030afd02973c9f0cab8e70c8f''"

definition current_profile_obligation_registry_sha256 :: string where
  "current_profile_obligation_registry_sha256 = ''54dac0857e45cfd5e1b98778b4b8ea1fbf02f4e9f87c0eaf4c78c9ce53f48bee''"

definition current_profile_tcb_root_sha256 :: string where
  "current_profile_tcb_root_sha256 = ''baf66d7f1ba3e09b9d03ee55dee4bfd8ff5ba3ada3f3d38c139fdfa9f1ab1243''"

definition current_profile_summary_root_sha256 :: string where
  "current_profile_summary_root_sha256 = ''d44aef4400e4a91a9e73763341b13b49a53fe392543e73e23137a9b57190669a''"

definition current_profile_core_refinement_count :: nat where
  "current_profile_core_refinement_count = 49"

definition current_profile_supporting_count :: nat where
  "current_profile_supporting_count = 24"

definition current_profile_backlog_count :: nat where
  "current_profile_backlog_count = 6"

definition current_profile_legacy_carryover :: bool where
  "current_profile_legacy_carryover = False"

theorem current_profile_partition_is_exact:
  "current_profile_core_refinement_count + current_profile_supporting_count +
   current_profile_backlog_count = 79"
  by (simp add: current_profile_core_refinement_count_def current_profile_supporting_count_def
    current_profile_backlog_count_def)

theorem legacy_rows_are_not_current_qualified_by_default:
  "\<not> current_profile_legacy_carryover"
  by (simp add: current_profile_legacy_carryover_def)

end
