(* GENERATED by scripts/verify-obligation-ledger-v3.mjs. DO NOT EDIT. *)
theory TRUST_Obligation_Ledger_Generated
  imports
    TRUST_End_To_End_Composition
    TRUST_Verified_Profile_Onboarding
    TRUST_Reusable_Summaries
    TRUST_Decoder_Guard_Words
    TRUST_M4_Action_Reversal_Row_Corollaries
begin

definition obligation_ledger_sha256 :: string where
  "obligation_ledger_sha256 = ''79592a27f332b84cac51d6387c2214f0d1612e68e396ea214c6da4a58dff36b6''"

definition obligation_ledger_bridge_schema_sha256 :: string where
  "obligation_ledger_bridge_schema_sha256 = ''011d379deafc1e606fbc6734f7d0895ea3b598e73b86866f009e3e08b0309610''"

definition obligation_ledger_closure_status :: string where
  "obligation_ledger_closure_status = ''CONDITIONAL''"

definition obligation_ledger_row_ids :: "string list" where
  "obligation_ledger_row_ids =
    [''NAT-AUTH-01'',
     ''NAT-AUTH-02'',
     ''NAT-AUTH-03'',
     ''NAT-NONCE-01'',
     ''NAT-NONCE-02'',
     ''NAT-NONCE-03'',
     ''NAT-STALE-01'',
     ''NAT-STALE-02'',
     ''NAT-STALE-03'',
     ''NAT-SHAPE-01'',
     ''NAT-SHAPE-02'',
     ''NAT-SHAPE-03'',
     ''NAT-SHAPE-04'',
     ''NAT-SHAPE-05'',
     ''NAT-CASE-01'',
     ''NAT-CASE-02'',
     ''NAT-CASE-03'',
     ''NAT-CASE-04'',
     ''NAT-CASE-05'',
     ''NAT-CASE-06'',
     ''NAT-CASE-07'',
     ''NAT-FRZ-01'',
     ''NAT-RSTR-01'',
     ''NAT-CUST-01'',
     ''NAT-CUST-02'',
     ''NAT-CUST-03'',
     ''NAT-DISP-01'',
     ''NAT-DISP-02'',
     ''NAT-DISP-03'',
     ''NAT-REV-01'',
     ''NAT-REV-02'',
     ''NAT-REV-03'',
     ''NAT-REV-04'',
     ''NAT-REV-05'',
     ''NAT-REV-06'',
     ''NAT-REV-07'',
     ''NAT-XFER-01'',
     ''NAT-XFER-02'',
     ''NAT-DEP-01'',
     ''NAT-DEP-02'',
     ''NAT-RCPT-01'',
     ''NAT-RCPT-02'',
     ''NAT-FAIL-01'',
     ''NAT-ROUTE-01'',
     ''NAT-ROUTE-02'',
     ''NAT-RETR-01'',
     ''NAT-E2E-01'',
     ''ADP-AUTH-01'',
     ''ADP-AUTH-02'',
     ''ADP-NONCE-01'',
     ''ADP-STALE-01'',
     ''ADP-SHAPE-01'',
     ''ADP-SHAPE-02'',
     ''ADP-CASE-01'',
     ''ADP-FRZ-01'',
     ''ADP-REV-01'',
     ''ADP-DISP-01'',
     ''ADP-CUST-01'',
     ''ADP-IMPORT-01'',
     ''ADP-UPSTREAM-01'',
     ''ADP-DEP-01'',
     ''ADP-RCPT-01'',
     ''ADP-OBS-01'',
     ''ADP-ROUTE-01'',
     ''ADP-SEAL-01'',
     ''ADP-PROFILE-01'',
     ''ADP-E2E-01'',
     ''GOV-SEAL-01'',
     ''SHR-ABI-01'',
     ''SHR-DEC-01'',
     ''SHR-DEC-02'',
     ''SHR-STATE-01'',
     ''SHR-NF-01'',
     ''SHR-ROW-01'']"

definition obligation_ledger_current_mandatory_rows :: "string list" where
  "obligation_ledger_current_mandatory_rows =
    []"

text \<open>
  Each row below names the Isabelle facts that state its abstract condition.
  The build fails when a cited fact no longer exists, so the ledger cannot
  drift from the theories it points into.
\<close>

lemmas obligation_row_NAT_AUTH_01 = authority_admits_def forward_authorized_def reversal_authorized_def unauthorized_sender_is_rejected unknown_authority_is_rejected successful_transaction_was_authorized_by_its_sender
lemmas obligation_row_NAT_AUTH_02 = stale_authority_epoch_is_rejected rotate_authority_def authority_rotation_makes_prior_commands_stale
lemmas obligation_row_NAT_NONCE_01 = forward_nonce_key_def reversal_nonce_key_def forward_fresh_def reversal_fresh_def reused_nonce_is_not_fresh forward_success_consumes_nonce_and_command_id
lemmas obligation_row_NAT_NONCE_02 = replayed_action_is_not_fresh successful_action_is_not_fresh_afterwards
lemmas obligation_row_NAT_NONCE_03 = replayed_reversal_is_not_fresh reversal_fresh_def
lemmas obligation_row_NAT_STALE_01 = forward_current_dependency_def stale_dependency_root_is_not_current stale_dependency_epoch_is_not_current rebind_dependency_def rebind_makes_prior_commands_stale rebind_advances_the_global_epoch_by_one forward_success_preserves_dependency_state
lemmas obligation_row_NAT_STALE_02 = reversal_current_dependency_def rebind_makes_prior_reversals_stale
lemmas obligation_row_NAT_STALE_03 = rebind_dependency_def rebind_advances_the_global_epoch_by_one
lemmas obligation_row_NAT_SHAPE_01 = forward_shape_wf_def malformed_input_is_persistent_stutter
lemmas obligation_row_NAT_SHAPE_02 = typed_decoder_sound_def successful_forward_transaction_is_admitted
lemmas obligation_row_NAT_SHAPE_03 = within_window_def forward_in_window_def reversal_in_window_def expired_window_is_rejected
lemmas obligation_row_NAT_SHAPE_04 = overlay_shape_def transfer_shape_def disposition_wf_def forward_shape_wf_def direct_disposition_requires_source_to_be_the_subject
lemmas obligation_row_NAT_SHAPE_05 = native_action_decodes_iff_canonical native_reversal_decodes_iff_canonical native_calldata_lengths_are_exact noncanonical_action_length_is_rejected noncanonical_reversal_length_is_rejected dirty_action_enum_high_bits_are_rejected dirty_action_address_high_bits_are_rejected dirty_action_uint48_high_bits_are_rejected dirty_action_uint64_high_bits_are_rejected unknown_selector_is_rejected
lemmas obligation_row_NAT_CASE_01 = terminal_case_rejects_action overlay_admissible_def
lemmas obligation_row_NAT_CASE_02 = overlay_on_open_case_without_head_is_rejected cross_case_overlay_head_is_rejected cross_case_restriction_head_is_rejected opened_overlay_def
lemmas obligation_row_NAT_CASE_03 = restrict_would_not_change_state_def second_restrict_in_own_case_is_rejected
lemmas obligation_row_NAT_CASE_04 = second_seize_in_open_case_is_rejected disposition_on_open_overlay_case_is_rejected no_disposition_commitments_def
lemmas obligation_row_NAT_CASE_05 = opened_overlay_def opened_custody_def
lemmas obligation_row_NAT_CASE_06 = confiscate_success_is_terminal liquidate_success_is_terminal recover_success_is_terminal disposed_case_def closed_case_def
lemmas obligation_row_NAT_CASE_07 = case_terminality_is_scoped disposition_in_one_case_does_not_clear_another_overlay freeze_preserves_restriction_overlay restrict_preserves_freeze_overlay
lemmas obligation_row_NAT_FRZ_01 = freeze_success_sets_absolute_target freeze_success_requires_strict_increase freeze_success_pushes_the_live_head freeze_success_records_prior_target freeze_success_opens_or_amends_the_freeze_case pushed_head_def pushed_link_def
lemmas obligation_row_NAT_RSTR_01 = restrict_success_sets_flag restrict_success_records_prior_flag freeze_and_restriction_are_independent
lemmas obligation_row_NAT_CUST_01 = seize_success_opens_custody seize_success_moves_exact_amount_to_custodian opened_custody_def seize_cannot_spend_custody_backing
lemmas obligation_row_NAT_CUST_02 = unbacked_available_def direct_disposition_cannot_spend_custody_backing ordinary_transfer_cannot_spend_the_frozen_floor_or_custody_backing
lemmas obligation_row_NAT_CUST_03 = custody_matches_def uses_active_custody_def custody_disposition_requires_the_exact_custody_record custody_disposition_consumes_the_custody_record close_custody_def
lemmas obligation_row_NAT_DISP_01 = disposition_success_moves_exact_amount confiscate_does_not_burn forward_success_preserves_total_supply reversal_success_preserves_total_supply move_balance_def
lemmas obligation_row_NAT_DISP_02 = liquidate_success_binds_settlement_in_receipt forward_external_commitment_def
lemmas obligation_row_NAT_DISP_03 = recover_success_consumes_entitlement consumed_entitlement_is_rejected
lemmas obligation_row_NAT_REV_01 = reversal_pairs_def mispaired_reversal_is_not_admissible unknown_original_is_not_admissible missing_reversal_provenance_is_not_admissible
lemmas obligation_row_NAT_REV_02 = reversal_current_effect_def reversal_admissible_def stale_freeze_reversal_is_not_admissible stale_restriction_reversal_is_not_admissible reversed_action_cannot_be_reversed_again unfreeze_requires_the_target_of_the_original
lemmas obligation_row_NAT_REV_03 = terminal_case_rejects_reversal
lemmas obligation_row_NAT_REV_04 = unfreeze_success_restores_prior_target unfreeze_reopens_the_case_when_a_parent_remains unfreeze_closes_the_case_when_the_chain_is_empty popped_head_def reopened_or_closed_def link_parent_def
lemmas obligation_row_NAT_REV_05 = unrestrict_success_restores_prior_flag_and_closes_case
lemmas obligation_row_NAT_REV_06 = release_success_returns_custody_and_closes_case release_requires_the_exact_active_custody
lemmas obligation_row_NAT_REV_07 = reversal_success_marks_the_original_reversed receipt_matches_reversal_def forward_and_reversal_receipts_are_distinguished_by_kind
lemmas obligation_row_NAT_XFER_01 = ordinary_transfer_allowed_def ordinary_transfer_respects_restriction_flags
lemmas obligation_row_NAT_XFER_02 = ordinary_transfer_state_def ordinary_transfer_preserves_regulatory_state
lemmas obligation_row_NAT_DEP_01 = classify_dependency_def bound_dependency_canonical_approval_classifies_applicable bound_dependency_canonical_denial_is_typed_rejection dependency_malformed_response_is_reason_202 dependency_echo_failure_is_reason_203 dependency_canonical_operational_is_reason_204 dependency_never_applies_without_matching_echoes dependency_denial_or_operational_failure_stutters dependency_outcome_post_def dependency_applicable_admits_the_transition
lemmas obligation_row_NAT_DEP_02 = dependency_identity_failure_is_reason_200 dependency_configuration_failure_is_reason_201 dependency_outcome_post_def dependency_applicable_admits_the_transition
lemmas obligation_row_NAT_RCPT_01 = receipt_matches_forward_def abstraction_receipt_def canonical_receipt_trace_def success_has_final_canonical_receipt_event success_returns_the_stored_receipt_hash committed_history_excludes_failure_receipts
lemmas obligation_row_NAT_RCPT_02 = receipt_matches_forward_def forward_and_reversal_receipts_are_distinguished_by_kind
lemmas obligation_row_NAT_FAIL_01 = abstract_failure_transition_def rejection_is_persistent_stutter operational_failure_is_persistent_stutter malformed_input_is_persistent_stutter dependency_failure_is_persistent_stutter rejected_transaction_is_abstract_stutter operational_transaction_is_abstract_stutter malformed_transaction_is_abstract_stutter dependency_revert_is_abstract_stutter
lemmas obligation_row_NAT_ROUTE_01 = native_routes_are_exhaustive typed_command_selectors_are_classified_as_kernel_commands typed_command_selectors_are_not_failure_selectors generic_dispatcher_selector_is_unclassified native_routes_def
lemmas obligation_row_NAT_ROUTE_02 = kernel_interface_id_def native_route_interface_id_def
lemmas obligation_row_NAT_RETR_01 = pinned_runtime_def projected_compositional_state_def alpha_current_def alpha_current_requires_exact_runtime alpha_current_rejects_runtime_substitution alpha_current_binds_the_generated_bridge_schema nonce_projection_is_exact freeze_and_restriction_projections_are_independent custody_backing_projection_is_exact case_record_projection_is_exact dependency_state_projection_is_exact authority_projection_is_exact receipt_projection_is_exact current_state_does_not_assume_history pinned_runtime_pins_every_footprint_address inhabitant_configuration_is_well_formed current_configuration_wf_is_inhabited inhabitant_pins_the_endpoint_code
lemmas obligation_row_NAT_E2E_01 = pinned_runtime_refinement.runtime_execution_implements_concrete_transaction pinned_runtime_refinement.successful_reversal_never_targets_a_terminal_case heterogeneous_composition_is_conditional_until_certificate compiler_correctness_remains_a_nonclaim pinned_runtime_refinement.end_to_end_refinement_under_runtime_link
lemmas obligation_row_ADP_AUTH_01 = profile_authorities_def profile_authorization_is_exactly_the_immutable_authority
lemmas obligation_row_ADP_AUTH_02 = profile_authority_cannot_rotate_by_a_command
lemmas obligation_row_ADP_NONCE_01 = reused_nonce_is_not_fresh replayed_action_is_not_fresh replayed_reversal_is_not_fresh forward_success_consumes_nonce_and_command_id
lemmas obligation_row_ADP_STALE_01 = stale_dependency_root_is_not_current stale_dependency_epoch_is_not_current forward_current_dependency_def reversal_current_dependency_def
lemmas obligation_row_ADP_SHAPE_01 = forward_shape_wf_def expired_window_is_rejected overlay_shape_def transfer_shape_def disposition_wf_def
lemmas obligation_row_ADP_SHAPE_02 = native_action_decodes_iff_canonical noncanonical_action_length_is_rejected noncanonical_reversal_length_is_rejected
lemmas obligation_row_ADP_CASE_01 = terminal_case_rejects_action overlay_on_open_case_without_head_is_rejected cross_case_overlay_head_is_rejected second_restrict_in_own_case_is_rejected second_seize_in_open_case_is_rejected confiscate_success_is_terminal disposed_case_def
lemmas obligation_row_ADP_FRZ_01 = saturated_target_def resynchronisation_reaches_the_saturated_target resynchronisation_never_lowers_an_owned_frozen_amount resynchronise_def saturated_target_is_bounded_by_target_and_balance
lemmas obligation_row_ADP_REV_01 = reversal_pairs_def reversal_current_effect_def unfreeze_success_restores_prior_target unfreeze_reopens_the_case_when_a_parent_remains terminal_case_rejects_reversal
lemmas obligation_row_ADP_DISP_01 = recover_success_consumes_entitlement consumed_entitlement_is_rejected
lemmas obligation_row_ADP_CUST_01 = profile_custody_confined_def confined_seize_is_a_kernel_seize
lemmas obligation_row_ADP_IMPORT_01 = import_entry_state_def imported_state_def imported_head_record_def open_imported_case_def empty_manifest_changes_no_declared_state imported_entry_declares_the_frozen_target_and_flag imported_frozen_entry_opens_a_reversible_freeze_case imported_freeze_head_admits_its_unfreeze import_case_ids_are_injective
lemmas obligation_row_ADP_UPSTREAM_01 = owned_upstream_state_def unowned_upstream_state_is_an_operational_stutter resynchronisation_never_lowers_an_owned_frozen_amount resynchronisation_reaches_the_saturated_target upstream_guarded_transition_def owned_upstream_state_admits_the_transition forced_transfer_restrictions_match_def restriction_poststate_guarded_transition_def forced_transfer_restriction_mismatch_is_an_operational_stutter resynchronise_def resynchronisation_changes_no_other_account
lemmas obligation_row_ADP_DEP_01 = dependency_identity_failure_is_reason_200 dependency_configuration_failure_is_reason_201 dependency_denial_or_operational_failure_stutters dependency_outcome_post_def dependency_applicable_admits_the_transition
lemmas obligation_row_ADP_RCPT_01 = receipt_matches_forward_def receipt_matches_reversal_def success_has_final_canonical_receipt_event success_returns_the_stored_receipt_hash forward_and_reversal_receipts_are_distinguished_by_kind
lemmas obligation_row_ADP_OBS_01 = actual_restriction_observation_def restriction_observation_reads_actual_upstream_flags
lemmas obligation_row_ADP_ROUTE_01 = profile_adapter_routes_are_exhaustive profile_adapter_routes_def erc3643_partial_interface_id_def
lemmas obligation_row_ADP_SEAL_01 = import_entry_state_def empty_manifest_changes_no_declared_state profile_authorities_def
lemmas obligation_row_ADP_PROFILE_01 = current_erc3643_reference_class_def current_erc3643_reference_is_partial_not_verified_full
lemmas obligation_row_ADP_E2E_01 = heterogeneous_composition_is_conditional_until_certificate pinned_runtime_refinement.end_to_end_refinement_under_runtime_link
lemmas obligation_row_GOV_SEAL_01 = manifest_canonical_def import_case_ids_are_injective import_case_id_def
lemmas obligation_row_SHR_ABI_01 = action_code_is_exact reversal_code_is_exact generated_calldata_lengths_are_exact runtimes_are_within_the_eip170_limit reason_codes_are_distinct case_transition_rule_ids_are_distinct
lemmas obligation_row_SHR_DEC_01 = c0_exact_length_gate_accepts_iff_shape_length c0_unsigned_guard_accepts_iff_word_fits c0_enum_guard_accepts_iff_below_bound c0_action_canonicality_is_exact_guard_conjunction c0_reversal_canonicality_is_exact_guard_conjunction
lemmas obligation_row_SHR_DEC_02 = guard_mask_and_uint_bounds decoder_uint48_guard_hypotheses_redundant decoder_uint64_guard_hypotheses_redundant decoder_uint160_guard_hypotheses_redundant masked_word_satisfies_unsigned_guard
lemmas obligation_row_SHR_STATE_01 = custody_consistent_def required_floor_def ordinary_available_def custody_backing_equals_active_custody_sum physical_balance_covers_custody_backing required_floor_is_additive_without_double_counting ordinary_available_plus_required_floor ordinary_available_never_spends_custody_backing ordinary_available_never_spends_own_frozen_floor unbounded_freeze_target_saturates_only_at_observation settlement_pair_commitment_is_injective
lemmas obligation_row_SHR_NF_01 = sparse_join_def owned_domain_def derived_slots_def owned_sparse_projection_reassembles shared_frame_is_preserved finite_declared_preimages_yield_nonalias_slots compiler_layout_labels_are_distinct
lemmas obligation_row_SHR_ROW_01 = act03_terminal_flag_omission_is_distinguished act04_custody_terminal_flag_omission_is_distinguished act05_settlement_omission_is_distinguished act06_custody_settlement_omission_is_distinguished act07_restriction_flag_omission_is_distinguished act08_entitlement_omission_is_distinguished act09_custody_entitlement_omission_is_distinguished rvr01_prior_amount_restoration_omission_is_distinguished rvr02_terminal_flag_omission_is_distinguished rvr03_prior_flag_restoration_omission_is_distinguished

theorem obligation_ledger_rows_are_distinct:
  "distinct obligation_ledger_row_ids"
  by (simp add: obligation_ledger_row_ids_def)

theorem obligation_ledger_has_no_current_mandatory_rows:
  "obligation_ledger_current_mandatory_rows = []"
  by (simp add: obligation_ledger_current_mandatory_rows_def)

theorem obligation_ledger_binds_the_generated_bridge:
  "obligation_ledger_bridge_schema_sha256 = runtime_bridge_schema_sha256"
  by (simp add: obligation_ledger_bridge_schema_sha256_def runtime_bridge_schema_sha256_def)

theorem obligation_ledger_closure_status_is_declared:
  "obligation_ledger_closure_status = ''CONDITIONAL''"
  by (simp add: obligation_ledger_closure_status_def)

end
