(* GENERATED by scripts/generate-runtime-bridge.mjs. DO NOT EDIT. *)
theory TRUST_Runtime_Bridge_Generated
  imports TRUST_Concrete_Configuration
begin

definition runtime_bridge_schema_sha256 :: string where
  "runtime_bridge_schema_sha256 = ''f087342d0eaa57a02468ff78e553ad42bb25fe027e833f311a5d0caac72383b7''"

definition compiler_binding_root_sha256 :: string where
  "compiler_binding_root_sha256 = ''44c62545b9545741bce98b313f412914bc976430c5596de6ad735f68d81cd4ab''"

definition constructor_fixture_root_sha256 :: string where
  "constructor_fixture_root_sha256 = ''b5ce284d6b7017a1feff3244bb67f175303660d86348ce93dbd8065bd39d3a2d''"

definition native_resolved_runtime_sha256 :: string where
  "native_resolved_runtime_sha256 = ''3697706d4948c34fada47e049d32ad3e1866cf24ded6328f0c209d858614a86d''"

definition profile_resolved_runtime_sha256 :: string where
  "profile_resolved_runtime_sha256 = ''0c873ae5756cf6a3e3ab1317af7c09a39391640b3c54bef4b84b091042d9cf4b''"

definition action_calldata_length :: nat where "action_calldata_length = 676"
definition reversal_calldata_length :: nat where "reversal_calldata_length = 292"
definition action_entrypoint_selector :: nat where
  "action_entrypoint_selector = 2644653369"
definition reversal_entrypoint_selector :: nat where
  "reversal_entrypoint_selector = 2058032795"
definition generic_dispatcher_input_selector :: nat where
  "generic_dispatcher_input_selector = 4294967295"
definition trust_operational_failure_selector :: nat where
  "trust_operational_failure_selector = 946785368"
definition trust_rejected_selector :: nat where
  "trust_rejected_selector = 2364935023"
definition typed_command_entrypoint_selectors :: "nat set" where
  "typed_command_entrypoint_selectors =
    {action_entrypoint_selector, reversal_entrypoint_selector}"
definition typed_failure_selectors :: "nat set" where
  "typed_failure_selectors =
    {trust_operational_failure_selector, trust_rejected_selector}"

fun solidity_action_code :: "legal_action_kind => nat" where
  "solidity_action_code Legal_Freeze = 0"
| "solidity_action_code Legal_Seize = 1"
| "solidity_action_code Legal_Confiscate = 2"
| "solidity_action_code Legal_Liquidate = 3"
| "solidity_action_code Legal_Restrict = 4"
| "solidity_action_code Legal_Recover = 5"

fun solidity_reversal_code :: "trust_reversal_kind => nat" where
  "solidity_reversal_code TRUST_UNFREEZE = 0"
| "solidity_reversal_code TRUST_RELEASE = 1"
| "solidity_reversal_code TRUST_UNRESTRICT = 2"

datatype native_storage_field = Native_Field_0 | Native_Field_1 | Native_Field_2 | Native_Field_3 | Native_Field_4 | Native_Field_5 | Native_Field_6 | Native_Field_7 | Native_Field_8 | Native_Field_9 | Native_Field_10 | Native_Field_11 | Native_Field_12 | Native_Field_13 | Native_Field_14 | Native_Field_15 | Native_Field_16 | Native_Field_17 | Native_Field_18 | Native_Field_19 | Native_Field_20 | Native_Field_21 | Native_Field_22 | Native_Field_23 | Native_Field_24 | Native_Field_25 | Native_Field_26 | Native_Field_27
datatype profile_storage_field = Profile_Field_0 | Profile_Field_1 | Profile_Field_2 | Profile_Field_3 | Profile_Field_4 | Profile_Field_5 | Profile_Field_6 | Profile_Field_7 | Profile_Field_8 | Profile_Field_9 | Profile_Field_10 | Profile_Field_11 | Profile_Field_12

fun native_storage_base_slot :: "native_storage_field => nat" where
  "native_storage_base_slot Native_Field_0 = 0"
|  "native_storage_base_slot Native_Field_1 = 1"
|  "native_storage_base_slot Native_Field_2 = 2"
|  "native_storage_base_slot Native_Field_3 = 3"
|  "native_storage_base_slot Native_Field_4 = 4"
|  "native_storage_base_slot Native_Field_5 = 5"
|  "native_storage_base_slot Native_Field_6 = 6"
|  "native_storage_base_slot Native_Field_7 = 7"
|  "native_storage_base_slot Native_Field_8 = 8"
|  "native_storage_base_slot Native_Field_9 = 9"
|  "native_storage_base_slot Native_Field_10 = 10"
|  "native_storage_base_slot Native_Field_11 = 11"
|  "native_storage_base_slot Native_Field_12 = 12"
|  "native_storage_base_slot Native_Field_13 = 13"
|  "native_storage_base_slot Native_Field_14 = 14"
|  "native_storage_base_slot Native_Field_15 = 15"
|  "native_storage_base_slot Native_Field_16 = 16"
|  "native_storage_base_slot Native_Field_17 = 17"
|  "native_storage_base_slot Native_Field_18 = 18"
|  "native_storage_base_slot Native_Field_19 = 19"
|  "native_storage_base_slot Native_Field_20 = 20"
|  "native_storage_base_slot Native_Field_21 = 21"
|  "native_storage_base_slot Native_Field_22 = 22"
|  "native_storage_base_slot Native_Field_23 = 23"
|  "native_storage_base_slot Native_Field_24 = 24"
|  "native_storage_base_slot Native_Field_25 = 29"
|  "native_storage_base_slot Native_Field_26 = 30"
|  "native_storage_base_slot Native_Field_27 = 31"

fun profile_storage_base_slot :: "profile_storage_field => nat" where
  "profile_storage_base_slot Profile_Field_0 = 0"
|  "profile_storage_base_slot Profile_Field_1 = 1"
|  "profile_storage_base_slot Profile_Field_2 = 2"
|  "profile_storage_base_slot Profile_Field_3 = 3"
|  "profile_storage_base_slot Profile_Field_4 = 4"
|  "profile_storage_base_slot Profile_Field_5 = 5"
|  "profile_storage_base_slot Profile_Field_6 = 6"
|  "profile_storage_base_slot Profile_Field_7 = 7"
|  "profile_storage_base_slot Profile_Field_8 = 8"
|  "profile_storage_base_slot Profile_Field_9 = 9"
|  "profile_storage_base_slot Profile_Field_10 = 10"
|  "profile_storage_base_slot Profile_Field_11 = 11"
|  "profile_storage_base_slot Profile_Field_12 = 12"

definition generated_projection_ids :: "string list" where
  "generated_projection_ids =
    [''native.actions'',
     ''native.allowances'',
     ''native.authorities'',
     ''native.balances'',
     ''native.bindings'',
     ''native.consumedEntitlements'',
     ''native.custody'',
     ''native.custodyBacking'',
     ''native.delegations'',
     ''native.effects'',
     ''native.entered'',
     ''native.entitlements'',
     ''native.freezeHeads'',
     ''native.frozen'',
     ''native.name'',
     ''native.pendingCommitments'',
     ''native.pendingReversals'',
     ''native.receipts'',
     ''native.restricted'',
     ''native.restrictionHeads'',
     ''native.routeTicket'',
     ''native.settlements'',
     ''native.symbol'',
     ''native.terminalCases'',
     ''native.totalSupply'',
     ''native.usedCommandIds'',
     ''native.usedGovernanceIds'',
     ''native.usedNonces'',
     ''profile.adapter.actions'',
     ''profile.adapter.consumedEntitlements'',
     ''profile.adapter.custody'',
     ''profile.adapter.custodyBacking'',
     ''profile.adapter.effects'',
     ''profile.adapter.entered'',
     ''profile.adapter.freezeHeads'',
     ''profile.adapter.frozenTargets'',
     ''profile.adapter.receipts'',
     ''profile.adapter.restrictionHeads'',
     ''profile.adapter.terminalCases'',
     ''profile.adapter.usedIds'',
     ''profile.adapter.usedNonces'',
     ''profile.governor.exclusiveAdapter'',
     ''profile.governor.sealedBinding'',
     ''profile.governor.topologySealed'',
     ''profile.token.balanceOf'',
     ''profile.token.exclusiveAgent'',
     ''profile.token.getFrozenTokens'',
     ''profile.token.isFrozen'',
     ''profile.token.owner'']"

definition required_refinement_obligation_ids :: "string list" where
  "required_refinement_obligation_ids =
    [''STATE-01'',
     ''STATE-02'',
     ''STATE-03'',
     ''STATE-04'',
     ''STATE-05'',
     ''STATE-06'',
     ''STATE-07'',
     ''STATE-08'',
     ''BAL-01'',
     ''BAL-02'',
     ''BAL-03'',
     ''BAL-04'',
     ''BAL-05'',
     ''BAL-06'',
     ''BAL-07'',
     ''BAL-08'',
     ''BAL-09'',
     ''BAL-10'',
     ''REV-01'',
     ''REV-02'',
     ''REV-03'',
     ''REV-04'',
     ''REV-05'',
     ''REV-06'',
     ''REV-07'',
     ''REV-08'',
     ''REV-09'',
     ''REV-10'',
     ''REV-11'',
     ''ABI-01'',
     ''ABI-02'',
     ''ABI-03'',
     ''ABI-04'',
     ''ABI-05'',
     ''AUTH-01'',
     ''AUTH-02'',
     ''AUTH-03'',
     ''AUTH-04'',
     ''AUTH-05'',
     ''ACT-01'',
     ''ACT-02'',
     ''ACT-03'',
     ''ACT-04'',
     ''ACT-05'',
     ''ACT-06'',
     ''ACT-07'',
     ''ACT-08'',
     ''ACT-09'',
     ''RVR-01'',
     ''RVR-02'',
     ''RVR-03'',
     ''FAIL-01'',
     ''FAIL-02'',
     ''FAIL-03'',
     ''FAIL-04'',
     ''FAIL-05'',
     ''FAIL-06'',
     ''FAIL-07'',
     ''FAIL-08'',
     ''EXT-01'',
     ''EXT-02'',
     ''EXT-03'',
     ''EXT-04'',
     ''EXT-05'',
     ''EXT-06'',
     ''EXT-07'',
     ''SEP-01'',
     ''SEP-02'',
     ''SEP-03'',
     ''SEP-04'',
     ''SEP-05'',
     ''ART-01'',
     ''ART-02'',
     ''ART-03'',
     ''ART-04'',
     ''ART-05'',
     ''ART-06'',
     ''ART-07'',
     ''ART-08'']"

theorem action_code_is_exact:
  "set (map solidity_action_code
    [Legal_Freeze, Legal_Seize, Legal_Confiscate,
     Legal_Liquidate, Legal_Restrict, Legal_Recover]) = {0, 1, 2, 3, 4, 5}"
  by simp

theorem reversal_code_is_exact:
  "set (map solidity_reversal_code
    [TRUST_UNFREEZE, TRUST_RELEASE, TRUST_UNRESTRICT]) = {0, 1, 2}"
  by simp

theorem generated_calldata_lengths_are_exact:
  "action_calldata_length = 676 & reversal_calldata_length = 292"
  by (simp add: action_calldata_length_def reversal_calldata_length_def)

theorem generated_projection_ids_are_distinct:
  "distinct generated_projection_ids"
  by (simp add: generated_projection_ids_def)

theorem required_refinement_obligation_inventory_is_exact:
  "length required_refinement_obligation_ids = 79 &
   distinct required_refinement_obligation_ids"
  by (simp add: required_refinement_obligation_ids_def)

end
