(* GENERATED by formal/kevm/row-bundles/bal-06/prepare-mutant.mjs. DO NOT EDIT. *)
theory BAL_06_Bridge_Generated
  imports ERC_TRUST.TRUST_Runtime_Bridge_Generated
begin

definition bal06_transfer_selector :: nat where
  "bal06_transfer_selector = 2835717307"

definition bal06_balances_base_slot :: nat where
  "bal06_balances_base_slot = 3"

definition bal06_frozen_base_slot :: nat where
  "bal06_frozen_base_slot = 5"

definition bal06_restricted_base_slot :: nat where
  "bal06_restricted_base_slot = 6"

definition bal06_backing_base_slot :: nat where
  "bal06_backing_base_slot = 7"

definition bal06_entered_scalar_slot :: nat where
  "bal06_entered_scalar_slot = 29"

definition bal06_symbolic_storage_key_count :: nat where
  "bal06_symbolic_storage_key_count = 10"

definition bal06_pairwise_key_nonalias_count :: nat where
  "bal06_pairwise_key_nonalias_count = 45"

definition bal06_rest_map_key_exclusion_count :: nat where
  "bal06_rest_map_key_exclusion_count = 10"

definition bal06_calldata_byte_length :: nat where
  "bal06_calldata_byte_length = 68"

definition bal06_address_zero_prefix_bytes :: nat where
  "bal06_address_zero_prefix_bytes = 12"

definition bal06_destination_payload_bytes :: nat where
  "bal06_destination_payload_bytes = 20"

definition bal06_amount_payload_bytes :: nat where
  "bal06_amount_payload_bytes = 32"

record bal06_runtime_view =
  bal06_source_balance :: nat
  bal06_destination_balance :: nat
  bal06_source_frozen :: nat
  bal06_destination_frozen :: nat
  bal06_source_backing :: nat
  bal06_destination_backing :: nat
  bal06_other_balance :: nat
  bal06_entered :: nat

definition bal06_runtime_transfer_post ::
  "bal06_runtime_view \<Rightarrow> nat \<Rightarrow> bal06_runtime_view"
where
  "bal06_runtime_transfer_post view amount =
     view\<lparr>bal06_source_balance := bal06_source_balance view - amount,
          bal06_destination_balance := bal06_destination_balance view + amount,
          bal06_entered := 0\<rparr>"

theorem generated_bal06_storage_projection_is_exact:
  "(bal06_transfer_selector,
    bal06_balances_base_slot,
    bal06_frozen_base_slot,
    bal06_restricted_base_slot,
    bal06_backing_base_slot,
    bal06_entered_scalar_slot,
    bal06_symbolic_storage_key_count,
    bal06_pairwise_key_nonalias_count,
    bal06_rest_map_key_exclusion_count,
    bal06_calldata_byte_length,
    bal06_address_zero_prefix_bytes,
    bal06_destination_payload_bytes,
    bal06_amount_payload_bytes) =
   (2835717307, 3, 5, 6, 7, 29, 10, 45, 10, 68, 12, 20, 32)"
  by (simp add: bal06_transfer_selector_def bal06_balances_base_slot_def
      bal06_frozen_base_slot_def bal06_restricted_base_slot_def
      bal06_backing_base_slot_def bal06_entered_scalar_slot_def
      bal06_symbolic_storage_key_count_def bal06_pairwise_key_nonalias_count_def
      bal06_rest_map_key_exclusion_count_def bal06_calldata_byte_length_def
      bal06_address_zero_prefix_bytes_def bal06_destination_payload_bytes_def
      bal06_amount_payload_bytes_def)

theorem generated_bal06_runtime_frame_is_exact:
  shows "bal06_source_balance (bal06_runtime_transfer_post view amount) =
         bal06_source_balance view - amount"
    and "bal06_destination_balance (bal06_runtime_transfer_post view amount) =
         bal06_destination_balance view + amount"
    and "bal06_source_frozen (bal06_runtime_transfer_post view amount) = bal06_source_frozen view"
    and "bal06_destination_frozen (bal06_runtime_transfer_post view amount) = bal06_destination_frozen view"
    and "bal06_source_backing (bal06_runtime_transfer_post view amount) = bal06_source_backing view"
    and "bal06_destination_backing (bal06_runtime_transfer_post view amount) = bal06_destination_backing view"
    and "bal06_other_balance (bal06_runtime_transfer_post view amount) = bal06_other_balance view"
    and "bal06_entered (bal06_runtime_transfer_post view amount) = 0"
  by (simp_all add: bal06_runtime_transfer_post_def)

end
