// SPDX-License-Identifier: BSD-3-Clause
// GENERATED by scripts/generate-normative-kernel.mjs from spec/erc-trust-kernel-v2.json. DO NOT EDIT.
// Kernel version 2. Deterministic, side-effect-free helpers for the
// ERC-TRUST kernel wire format. The helpers do not sign, submit, decide authority,
// or validate a deployment.

import { AbiCoder, Interface, ZeroHash, getAddress, id, keccak256 } from "ethers";

export const KERNEL_VERSION = 2;
export const KERNEL_DOMAIN = "0xb5303e4083d2781d6c7d6a68d30b6354ebda11f0a2a037b946d87b3eec40b74e";
export const DEPENDENCY_ROOT_TAG = "0x8dd0ff19b096a49997e6e0fa1eea2dee5d61291bb86d3d10640e517c9e6cbe18";
export const KERNEL_INTERFACE_ID = "0x2b020308";
export const PROFILE_IDS = {
  "native-full": "0x86ba25e1a29a74ad905fd84744be032fec9dc05645f58f7f1b7788dc60ae866b",
  "erc3643-verified-full": "0xad56e54f83cc255e391dd3838f7dc4befa1b0306b42d8ed7974588f27fec41ad",
} as const;
export const KERNEL_SELECTORS = {
  executeRegulatoryAction: "0x2f4e0773",
  executeRegulatoryReversal: "0x2b892e8f",
  deriveActionId: "0xfc6a9112",
  deriveReversalId: "0xf3315a6c",
  actionRecord: "0x330fcfde",
  receipt: "0x198a27aa",
  caseRecord: "0x2a408631",
  dependencyState: "0x7bf8f8b6",
  trustProfile: "0x5ba37779",
} as const;

export enum ActionKind {
  FREEZE = 0,
  SEIZE = 1,
  CONFISCATE = 2,
  LIQUIDATE = 3,
  RESTRICT = 4,
  RECOVER = 5,
}

export enum ReversalKind {
  UNFREEZE = 0,
  RELEASE = 1,
  UNRESTRICT = 2,
}

export enum ReceiptKind {
  NONE = 0,
  ACTION = 1,
  REVERSAL = 2,
}

export enum BindingKind {
  POLICY = 0,
  IDENTITY = 1,
  SETTLEMENT = 2,
  ENTITLEMENT = 3,
}

export enum AssessmentOutcome {
  APPLICABLE = 0,
  REJECTED = 1,
  OPERATIONAL_FAILURE = 2,
}

export enum Lifecycle {
  NONE = 0,
  PREPARED = 1,
  APPLIED = 2,
  REVERSED = 3,
}

export enum ProfileKind {
  UNSUPPORTED = 0,
  NATIVE_FULL = 1,
  VERIFIED_FULL = 2,
  PARTIAL = 3,
}

export enum CasePhase {
  NONE = 0,
  OPEN = 1,
  TERMINAL = 2,
}

export enum CaseFamily {
  NONE = 0,
  FREEZE = 1,
  RESTRICT = 2,
  CUSTODY = 3,
  DISPOSITION = 4,
}

export interface ActionRequest {
  domain: string;
  actionId: string;
  action: ActionKind;
  subject: string;
  source: string;
  destination: string;
  custodian: string;
  amount: bigint;
  caseId: string;
  dependencyRoot: string;
  dependencyEpoch: bigint;
  provenanceCommitment: string;
  settlementCommitment: string;
  proceedsCommitment: string;
  entitlementCommitment: string;
  authorityRef: string;
  authorityEpoch: bigint;
  nonce: bigint;
  validAfter: bigint;
  validBefore: bigint;
}

export interface ReversalRequest {
  domain: string;
  reversalId: string;
  actionId: string;
  reversal: ReversalKind;
  dependencyRoot: string;
  dependencyEpoch: bigint;
  provenanceCommitment: string;
  authorityRef: string;
  authorityEpoch: bigint;
  nonce: bigint;
  validAfter: bigint;
  validBefore: bigint;
}

export interface CaseRecord {
  phase: CasePhase;
  family: CaseFamily;
  headActionId: string;
  generation: bigint;
}

export interface ProfileDescriptor {
  profileId: string;
  profileKind: ProfileKind;
  standardVersion: bigint;
  actionMask: bigint;
  reversalMask: bigint;
  underlyingToken: string;
  manifestHash: string;
  full: boolean;
  proxySupported: boolean;
}

/** Every receipt field except receiptHash, in preimage order. */
export interface ReceiptInput {
  receiptKind: ReceiptKind;
  commandId: string;
  commandKind: bigint;
  parentCommandId: string;
  subject: string;
  source: string;
  destination: string;
  amount: bigint;
  caseId: string;
  authorityRef: string;
  dependencyRoot: string;
  provenanceCommitment: string;
  assessmentEvidence: string;
  preState: string;
  postState: string;
  externalCommitment: string;
}

export const ACTION_TUPLE = "tuple(bytes32 domain,bytes32 actionId,uint8 action,address subject,address source,address destination,address custodian,uint256 amount,bytes32 caseId,bytes32 dependencyRoot,uint64 dependencyEpoch,bytes32 provenanceCommitment,bytes32 settlementCommitment,bytes32 proceedsCommitment,bytes32 entitlementCommitment,bytes32 authorityRef,uint64 authorityEpoch,uint256 nonce,uint48 validAfter,uint48 validBefore)";
export const REVERSAL_TUPLE = "tuple(bytes32 domain,bytes32 reversalId,bytes32 actionId,uint8 reversal,bytes32 dependencyRoot,uint64 dependencyEpoch,bytes32 provenanceCommitment,bytes32 authorityRef,uint64 authorityEpoch,uint256 nonce,uint48 validAfter,uint48 validBefore)";
export const RECEIPT_PREIMAGE_TYPES = ["bytes32","uint8","bytes32","uint8","bytes32","address","address","address","uint256","bytes32","bytes32","bytes32","bytes32","bytes32","bytes32","bytes32","bytes32"] as const;

const coder = AbiCoder.defaultAbiCoder();
const kernelInterface = new Interface([
  `function executeRegulatoryAction(${ACTION_TUPLE} request) returns (bytes32)`,
  `function executeRegulatoryReversal(${REVERSAL_TUPLE} request) returns (bytes32)`,
]);

export function normalizeActionRequest(request: ActionRequest): ActionRequest {
  return {
    ...request,
    subject: getAddress(request.subject),
    source: getAddress(request.source),
    destination: getAddress(request.destination),
    custodian: getAddress(request.custodian),
  };
}

function encodeCommand(tuple: string, endpoint: string, chainId: bigint, request: object): string {
  return keccak256(coder.encode(["bytes32", "address", "uint256", tuple], [KERNEL_DOMAIN, getAddress(endpoint), chainId, request]));
}

/** hashes.actionId: the request with actionId zeroed, bound to the endpoint and chain. */
export function deriveActionId(endpoint: string, chainId: bigint, request: ActionRequest): string {
  return encodeCommand(ACTION_TUPLE, endpoint, chainId, normalizeActionRequest({ ...request, actionId: ZeroHash }));
}

/** hashes.commandHash: the completed request including its actionId. */
export function commandHash(endpoint: string, chainId: bigint, request: ActionRequest): string {
  return encodeCommand(ACTION_TUPLE, endpoint, chainId, normalizeActionRequest(request));
}

/** hashes.reversalId: the request with reversalId zeroed, bound to the endpoint and chain. */
export function deriveReversalId(endpoint: string, chainId: bigint, request: ReversalRequest): string {
  return encodeCommand(REVERSAL_TUPLE, endpoint, chainId, { ...request, reversalId: ZeroHash });
}

/** hashes.reversalHash: the completed reversal request including its reversalId. */
export function reversalHash(endpoint: string, chainId: bigint, request: ReversalRequest): string {
  return encodeCommand(REVERSAL_TUPLE, endpoint, chainId, request);
}

/** hashes.bindingHash of the native profile. */
export function bindingHash(
  kind: BindingKind,
  dependency: string,
  runtimeCodeId: string,
  configurationDigest: string,
  schema: string,
  epoch: bigint,
): string {
  return keccak256(
    coder.encode(
      ["bytes32", "uint8", "address", "bytes32", "bytes32", "bytes32", "uint64"],
      [KERNEL_DOMAIN, kind, getAddress(dependency), runtimeCodeId, configurationDigest, schema, epoch],
    ),
  );
}

/** hashes.dependencyRoot over the four per-kind bindings in BindingKind order. */
export function dependencyRoot(policy: string, identity: string, settlement: string, entitlement: string): string {
  return keccak256(
    coder.encode(
      ["bytes32", "bytes32", "bytes32", "bytes32", "bytes32", "bytes32"],
      [KERNEL_DOMAIN, DEPENDENCY_ROOT_TAG, policy, identity, settlement, entitlement],
    ),
  );
}

/** hashes.nonceKey reported by TrustReplay. */
export function nonceKey(authorityRef: string, authorityEpoch: bigint, nonce: bigint): string {
  return keccak256(coder.encode(["bytes32", "bytes32", "uint64", "uint256"], [KERNEL_DOMAIN, authorityRef, authorityEpoch, nonce]));
}

/** The action-specific external commitment bound by an ACTION receipt. */
export function externalCommitmentFor(request: ActionRequest): string {
  if (request.action === ActionKind.LIQUIDATE) {
    return keccak256(coder.encode(["bytes32", "bytes32"], [request.settlementCommitment, request.proceedsCommitment]));
  }
  if (request.action === ActionKind.RECOVER) return request.entitlementCommitment;
  return ZeroHash;
}

/** hashes.receiptHash over the domain and every receipt field except receiptHash. */
export function receiptHash(input: ReceiptInput): string {
  return keccak256(
    coder.encode(
      [...RECEIPT_PREIMAGE_TYPES],
      [
        KERNEL_DOMAIN,
        input.receiptKind,
        input.commandId,
        input.commandKind,
        input.parentCommandId,
        getAddress(input.subject),
        getAddress(input.source),
        getAddress(input.destination),
        input.amount,
        input.caseId,
        input.authorityRef,
        input.dependencyRoot,
        input.provenanceCommitment,
        input.assessmentEvidence,
        input.preState,
        input.postState,
        input.externalCommitment,
      ],
    ),
  );
}

export function encodeAction(request: ActionRequest): string {
  return kernelInterface.encodeFunctionData("executeRegulatoryAction", [normalizeActionRequest(request)]);
}

export function encodeReversal(request: ReversalRequest): string {
  return kernelInterface.encodeFunctionData("executeRegulatoryReversal", [request]);
}

export function kernelSelector(signature: string): string {
  return id(signature).slice(0, 10);
}
