(* GENERATED by formal/kevm/row-bundles/state-04/prepare-mutant.mjs. DO NOT EDIT. *)
theory STATE_04_Bridge_Generated
  imports ERC_TRUST.TRUST_Runtime_Bridge_Generated
begin
definition state04_get_frozen_selector :: nat where "state04_get_frozen_selector = 361437783"
definition state04_frozen_base_slot :: nat where "state04_frozen_base_slot = 5"
definition state04_restricted_base_slot :: nat where "state04_restricted_base_slot = 6"
definition state04_calldata_byte_length :: nat where "state04_calldata_byte_length = 36"
record state04_runtime_view = state04_frozen_word :: nat state04_restricted_word :: nat
definition state04_decode_bool_word :: "nat \<Rightarrow> bool" where "state04_decode_bool_word word \<longleftrightarrow> word = 1"
definition state04_get_frozen_output :: "state04_runtime_view \<Rightarrow> nat" where "state04_get_frozen_output view = state04_frozen_word view"
definition state04_getter_post :: "state04_runtime_view \<Rightarrow> state04_runtime_view" where "state04_getter_post view = view"
theorem generated_state04_overlay_storage_projection_is_exact: "(state04_get_frozen_selector, state04_frozen_base_slot, state04_restricted_base_slot, state04_calldata_byte_length) = (361437783, 5, 6, 36)" by (simp add: state04_get_frozen_selector_def state04_frozen_base_slot_def state04_restricted_base_slot_def state04_calldata_byte_length_def)
theorem generated_state04_runtime_observation_is_exact: assumes "state04_frozen_word view = frozen" and "state04_restricted_word view = 1" shows "state04_get_frozen_output view = frozen" and "state04_decode_bool_word (state04_restricted_word view)" and "state04_frozen_word (state04_getter_post view) = frozen" and "state04_restricted_word (state04_getter_post view) = 1" using assms by (simp_all add: state04_get_frozen_output_def state04_decode_bool_word_def state04_getter_post_def)
end
